version: '3.5'
services:
  app:
    image: golang:1.10.3
    volumes:
      - .:/go/src/github.com/kimura-of-light/isucon8
    working_dir: /go/src/github.com/kimura-of-light/isucon8
    command: go get -u github.com/golang/dep/cmd/dep && go run app.go
    ports:
      - 80:8080
  db:
    image: mariadb:10.4
    volumes:
      #- ./docker/db/my.cnf:/etc/db/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d"
    ports:
      - 23306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=torb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci