[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.3"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.10"

[[constraint]]
  name = "github.com/labstack/echo-contrib"
  version = "0.5.2"

[prune]
  go-tests = true
  unused-packages = true
